### ISSUE TITLE
Rename hide_target to show_target (reversed logic)

### ISSUE THREAD

**Issue by grezniczek** [davwillev/stopwatch#28]
And add a separate setting for surveys (show_target_survey)? Both false by default.
@davwillev , what do you think?

**Comment by davwillev** [comment]
Yes, I think this is a good idea, particularly if the results have already been displayed in the stopwatch field.
Can you think of a use case in which complete concealment of results is desirable? I can’t, but somebody might do. So probably best to keep display settings separate from target field settings

**Comment by grezniczek** [comment]
The results will always be visible in the stopwatch itself. When the target field is visible and editable, then users can write directly into these fields. If the format makes sense to the stopwatch, it will display that value (this would mostly be an issue for fields without validation).

For advanced stopwatches (laps, captures), the target field should mostly be hidden, as these contain either JSON or the "address" of the stopwatch data in the repeating instrument.

**Comment by davwillev** [comment]
I agree that the target field should typically be hidden in Advanced Stopwatches. Since it is already displayed in the stopwatch field, I can't see the need to view or edit these, especially when they can be reset by the stopwatch, if necessary (and configured to do so).

I was additionally wondering if there is a use case for a completely concealed result from a stopwatch field, so that the user (or participant) remains completely blinded to their result. I'm not sure that there is, but thought I'd ask you in any case.

**Comment by grezniczek** [comment]
Ah, I hadn't thought of this  ... but if the person entering the data should be blinded to the result, then the stopwatch should not display anything at all ...

However, this is already possible since the display can be configured freely. However, this is lacking a bit. I will (actually already have) expanded the display settings so that this can easily be achieved, with up to 3 states shown in a blinded case (no value yet, running, blinded value present). This will be in the next beta, which I probably will name rc.1 (release candidate).
